### ISSUE TITLE
Infinite recursion during resource lookup within System.Private.CoreLib

### ISSUE THREAD

**Issue by Nik-Kudrin** [AutomateThePlanet/Meissa#3]
Hi.

I have tried to start our API test on multiple machines.
Setup: 1 test agent, 1 test server (different machnines) (Windows)

Test start command:

`
PS C:\Users\kudrin.CORP\Downloads\Meissa> .\Meissa.exe runner --resultsFilePath="e:\Temp\MeissaResults\result.trx" --outputFilesLocation="E:\Repo\BCKAPI\mdm.webapi.mdmonli
ne.integrationtest\Mdm.WebApi.MdmOnline.IntegrationTest.Tests\bin\Debug\" --agentTag="MeissaAgent" --testTechnology="NUnit" --testLibraryPath="E:\Repo\BCKAPI\mdm.webapi.md
monline.integrationtest\Mdm.WebApi.MdmOnline.IntegrationTest.Tests\bin\Debug\Mdm.WebApi.MdmOnline.IntegrationTest.Tests.dll" --runInParallel --nativeRunnerArguments="--wor
kers=10" --testServerUrl="http://msk-ws27018:5000"
`

During the startup followed error happend:

`
 Created by Bellatrix Ltd.
 http://bellatrix.solutions
Test Execution started....
FROM TestRunnerPluginService ExecutePreTestRunLogic $$$$$$$$$$$$$$$
Assert Failure
Expression: [Recursive resource lookup bug]
Description: Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility
 points such as assembly resolve events or CultureInfo names.  Resource name: ArgumentNull_Generic
Stack Trace:
   at System.SR.InternalGetResourceString(String key)
   at System.SR.GetResourceString(String resourceKey, String defaultString)
   at System.ArgumentNullException..ctor(String paramName)
   at System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(Assembly assembly)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark,
IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackM
ark)
   at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExist
s, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at System.SR.InternalGetResourceString(String key)
   at System.SR.GetResourceString(String resourceKey, String defaultString)
   at System.ArgumentNullException..ctor(String paramName)
   at System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(Assembly assembly)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark,
IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackM
ark)
   at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExist
s, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at System.SR.InternalGetResourceString(String key)
   at System.SR.GetResourceString(String resourceKey, String defaultString)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Meissa.Plugins.NUnit.NativeTestsRunnerTestCasesPluginService.ExtractAllTestCasesFromTestLibrary(String testLibraryPath)
   at Meissa.Core.Services.TestExecutionService.<ExecuteAsync>d__19.MoveNext() in D:\SourceCode\AutomateThePlanet\Meissa\Meissa.Core.Services\TestExecutionService.cs:line
89
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
   at Meissa.Core.Services.TestRunProvider.<CreateNewTestRunAsync>d__7.MoveNext() in D:\SourceCode\AutomateThePlanet\Meissa\Meissa.Core.Services\TestRunProvider.cs:line 72

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
   at Meissa.API.Client.RestClientRepository`1.<CreateAsync>d__12.MoveNext() in D:\SourceCode\AutomateThePlanet\Meissa\Meissa.API.Client\DataSetupWebApi.cs:line 51
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
   at Meissa.API.Client.HttpClientExtensions.<SendAsyncWithRetry>d__0.MoveNext() in D:\SourceCode\AutomateThePlanet\Meissa\Meissa.API.Client\HttpClientExtensions.cs:line 5
6
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(Task`1 completedTask)
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__48.MoveNext()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(Task task, Boolean needsProtection)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(Task`1 completedTask)
   at System.Net.Http.WinHttpResponseStream.<CopyToAsyncCore>d__18.MoveNext()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
PS C:\Users\kudrin.CORP\Downloads\Meissa>

`

And it seems that 'nunitConsoleExePath' in 'meissaSettings.json' file wasn't described in documentation

`
{
    "testAgent": {
.....

        "nunitConsoleExePath": "C:\\NUnit\\nunit-console\\nunit3-console.exe"
....
    },
`

**Comment by angelovstanton** [comment]
Nik,

I think I found what the problem is. It is not a bug in the app but rather a [weird bug in .NET Core](https://github.com/dotnet/corefx/issues/24832). Anyhow, they claim that they have fixed it in the new versions of .NET Core, so I updated all NuGet packages as the first step. Next, they propose a workaround as setting the default culture of the app manually, so add this as well, now the default culture is en-US. 

You can find the new version [here](http://www.automatetheplanet.com/wp-content/uploads/2018/04/Windows-1.0.1.0.zip).

I will appreciate if you share if this fixed your issue since I couldn't reproduce it. 

Best,
Anton

**Comment by Nik-Kudrin** [comment]
Anton, 

Thank you for fast feedback and fix.
I'll try to use new version and will report result.

**Comment by Nik-Kudrin** [comment]
Anton,

I successfully run the tests.
So, I think, this issue could be closed.

Thank you, for your fix.  We will try next step - split tests across multiple machines.

**Comment by angelovstanton** [comment]
Nik,

Glad the fix worked. Hope everything else works as expected. If there is something, just drop a line and I will look into it. :)

Anton

**Comment by angelovstanton** [comment]
FIXED and VERIFIED
